<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Aiursoft.Kanban.MySql</AssemblyName>
    <RootNamespace>Aiursoft.Kanban.MySql</RootNamespace>
    <IsTestProject>false</IsTestProject>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aiursoft.Kanban.Entities\Aiursoft.Kanban.Entities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aiursoft.DbTools.MySql" Version="10.0.22" />
  </ItemGroup>
</Project>